=== BorisovskiP/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Suite/etc/suiteSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configType"/>
    <xs:complexType name="groupType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:boolean" name="remove" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="cestType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="test" use="optional"/>
                <xs:attribute type="xs:boolean" name="remove" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="moduleType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
                <xs:attribute type="xs:string" name="file" use="optional"/>
                <xs:attribute type="xs:boolean" name="remove" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="includeType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="groupType" name="group" minOccurs="0"/>
            <xs:element type="cestType" name="cest" minOccurs="0"/>
            <xs:element type="moduleType" name="module" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="excludeType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="groupType" name="group" minOccurs="0"/>
            <xs:element type="cestType" name="cest" minOccurs="0"/>
            <xs:element type="moduleType" name="module" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="suiteType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="includeType" name="include" maxOccurs="1"/>
            <xs:element type="excludeType" name="exclude" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="configType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="suiteType" name="suite"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== BorisovskiP/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Suite/etc/sampleSuite.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="suiteSchema.xsd">
    <suite name="mySuite">
        <include>
            <group name="someGroup"/>
            <cest name="cest"  test=""/>
            <module name="moduleName" file="myFile"/>
        </include>
        <exclude>
            <group name="someGroup"/>
            <cest name="excludeTest" test=""/>
            <group name="excludeGroup"/>
            <module name="moduleName" file="excludeFile"/>
        </exclude>
    </suite>
</config>
